FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY ProjectCICD/pom.xml .
COPY ProjectCICD/.mvn .mvn
COPY ProjectCICD/mvnw .
COPY ProjectCICD/src src
RUN chmod +x mvnw && ./mvnw -B clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8082
ENTRYPOINT ["java", "-jar", "app.jar"]
