FROM node:20-alpine AS build
WORKDIR /app
COPY task-manager/package*.json ./
RUN npm ci
COPY task-manager/ ./
RUN npm run build

FROM nginx:alpine
COPY Docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
